### ISSUE TITLE
[BUG] New Issue

### ISSUE THREAD

**Issue by miriki** [The-EG/OctoPrint-UBLMeshEdit#16] opened 2022-01-24 16:50 UTC
**Describe the bug**
(I) No Mesh
The command completed successfully, but no mesh was detected. [...]

A plugin "bed visualizer" displays the mesh correctly.

**M420 Output**
```
Send: M420 V1 T1
Recv: Mesh Bed Level data:
Recv: 5x5 mesh. Z offset: 0.00000
Recv: Measured points:
Recv:         0        1        2        3        4
Recv:  0 -0.02000 -0.10000 -0.10000 -0.08000 -0.02000
Recv:  1 +0.02000 -0.06000 -0.06000 -0.04000 +0.02000
Recv:  2 +0.06000 -0.04000 -0.04000 -0.04000 +0.04000
Recv:  3 +0.06000 -0.04000 -0.04000 -0.03000 +0.04000
Recv:  4 +0.08000 -0.02000 -0.03000 -0.02000 +0.04000
Recv: 
Recv: echo:Bed Leveling ON
Recv: echo:Fade Height OFF
Recv: ok
```

**Firmware**
https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/releases/download/1.4.0-beta.4/MEGA_X_TMC_v1.4.0-b4.hex

**Comment by The-EG** [comment] 2022-01-24 17:09
Hi there,
I can see from the output that you are using `#define MESH_BED_LEVELING` not `#define AUTO_BED_LEVELING_UBL` which can be used without a probe if you also `#define PROBE_MANUALLY`. This plugin does not support MBL. There are too many odd quirks with it.

Duplicate of #12

**Closed as completed by The-EG** 2022-01-24 17:09 UTC
Labels: wontfix
